### ISSUE TITLE
MacOS - Onboard To Homebrew Package Manager

### ISSUE THREAD

**Issue by bartekpacia** [google/purr#1]
Hi!

First of all – thank you for this project, it looks very cool. I wish I had it a few weeks earlier when I was `adb logcat`-ing hundreds of time a day.

My request is to be able to `brew install purr` and have it available right away :)

**Comment by alpiccioni** [comment]
Hey Bartek,

Thanks for the kind words. I hope you keep finding it useful :)

I'll endeavour to get it on Homebrew. I can see that `fzf` has been updated to 0.40.0 on Hoembrew, which is the version I need, so I can likely collapse the script folder into just the `purr` script.

This is somewhat impeded by us not using Homebrew internally, so no promises on timing, I need to figure out how to sideload it.

Thanks!

**Comment by alpiccioni** [comment]
Didn't mean to close, reopenning.

**Comment by bartekpacia** [comment]
Hi @alpiccioni – I keep using `purr` and am loving it.

Could I try to contribute this if you don't have time?

**Comment by alpiccioni** [comment]
Hey Bartek, I'd really appreciate it! I've been slacking a bit on the packaging issues :P

**Comment by alpiccioni** [comment]
> Hi @alpiccioni – I keep using `purr` and am loving it.
> 
> Could I try to contribute this if you don't have time?

Just as a head's up, I am splitting purr up into source files that can be compiled into a single executable through a "make" command. I should push the final build by the end of the week. This might (should?) make it easier to package things up!

**Comment by bartekpacia** [comment]
That sounds great! I haven't yet started doing anything because of lack of time, but I hope to do it soon

**Comment by alpiccioni** [comment]
> That sounds great! I haven't yet started doing anything because of lack of time, but I hope to do it soon

No problem; do what you can when you can!

**Comment by bartekpacia** [comment]
Hi @alpiccioni, just checking in to ask if you have any plans to merge `code-restructure` to `master`? Then I could start homebrewing it:)

Also, I'd like to ask what's the motivation for bundling `fzf` in the repo? If `purr` will be onboarded to package managers (Homebrew, apt, pacman?), then I think that managing dependency on `fzf` should be that package manager's responsibility.

**Comment by alpiccioni** [comment]
Hey! Yup, slipped my mind. Let me get to it tomorrow and make sure it's running smooth and then merge it.

The code restructure should drop the `fzf` bundling. You are correct that it should be handled by the package manager! However, the core problem here is that part of the functionality relies on version `0.40.0`, and the Google-internal Linux version didn't support that version until recently. 

However, now that it's been updated, the bundled dependency should be removable.

**Comment by alpiccioni** [comment]
Awesome!

For the test block, if that becomes a problem, I can look into creating a bypass. I think testing `purr` is going to be very difficult because it exists on top of `fzf`, which is pretty opaque, so testing the UI would be difficult.

What I could do is create a test suite that initializes `purr` with a mocked ADB client, feeds it some data, and checks if the backing files have initialized correctly. That would at least check if it `purr` can boot correctly.

Thanks for doing this!

**Comment by alpiccioni** [comment]
Done. Thanks!

**Comment by alpiccioni** [comment]
Seeing from my work laptop:

```
> brew install purr
...
==> Summary
🍺  /opt/homebrew/Cellar/purr/2.0.4: 7 files, 86.8KB
> purr
Waiting on a device to connect...
```

Looks finished to me.

Thanks for the work on this @bartekpacia!

**Comment by bartekpacia** [comment]
Yeah! Huge thanks to you as well! I'll try packaging pure for AUR next (hopefully it'll reach `extra` after some time!)
