### ISSUE TITLE
Hardcoded binary locations at /usr/bin/

### ISSUE THREAD

**Issue by starsep** [google/purr#13]
## Expected Behavior
`purr` works when standard binaries are available on `$PATH`

## Actual Behavior
`purr` assumes for a few binaries that they are located in /usr/bin:
- /usr/bin/grep
- /usr/bin/head
- /usr/bin/sed 
- /usr/bin/sort
- /usr/bin/tail
- /usr/bin/touch
- /usr/bin/tr
- /usr/bin/wc

Usage of /usr/bin/env in shebang is not a problem.
## Steps to Reproduce the Problem
1. Run purr in NixOS

## Specifications
- Version: 2.0.4
- Platform: NixOS - Linux distro which is non-FHS compliant

## Possible solution
I considered doing something like 
```
TOUCH=$(which touch)
# ....
$TOUCH $purr_input_cache
```

But binaries are called from multiple scripts.
Is there a good place where location of binaries could be checked and then used from any script?

**Comment by alpiccioni** [comment]
I missed this issue a bit ago.

Let me check; the original reason I did this is for internal reasons 😅. This might be easily fixable.

**Comment by alpiccioni** [comment]
Pushed a fix. It likely won't go to homebrew (though I think that wouldn't really matter), but if you pull the latest code and compile it, it'll work.

Thanks for the report!
