### ISSUE TITLE
Not working on MacOS Sonoma, just hangs indefinitely

### ISSUE THREAD

**Issue by ConorGarry** [google/purr#14]
I want to try purr as my usecase involves working with a few apps simultaneously, but I could never get it it work.

## Expected Behavior
Logs to appear, like the gifs in the ReadMe.

## Actual Behavior
Nothing happens, calling `purr` just hangs indefinitely.

## Steps to Reproduce the Problem

1. Perhaps it's a permission issue so I've tried with `sudo`, which does give a slight different result. When it hangs indefinitely, I try `Ctrl C` which flashes some errors then launches purr but no logs show up, and the panel on the right shows an error:
`cat: /tmp/purr.tqSBUeQteg/instructions.purr: No such file or directory`
Then when I exit I see the errors that had flashed:
```
grep: /tmp/purr.tqSBUeQteg/stream-header.purr: No such file or directory
grep: /tmp/purr.tqSBUeQteg/stream-header.purr: No such file or directory
cat: /tmp/purr.tqSBUeQteg/preview-command-cache.purr: No such file or directory
cat: /tmp/purr.tqSBUeQteg/preview-visibility-cache.purr: No such file or directory
__purr_set_start_preview:24: no such file or directory: /tmp/purr.tqSBUeQteg/preview-command-cache.purr
__purr_set_start_preview:25: no such file or directory: /tmp/purr.tqSBUeQteg/preview-visibility-cache.purr
```

## Specifications

- Version: `2.0.4` installed via Homebrew.
- Platform: MacOS Sonoma `14.6.1`, 2023 M2 Max
- iTerm 2: `3.5.4`

**Comment by alpiccioni** [comment]
Hey Conor,

I performed the following steps:

1. Downloaded the repo from Github.
2. Ran `make`.
3. Ran ./out/purr

I'm using an AVD from Android Studio, but I don't think that should matter. I'm running on 14.6.1 and iterm 3.5.4 as well, but on an M1. That shouldn't make a difference, I think...

I also tried the Brew version, but I'm not seeing any issues there either. 

The error messages you are showing somehow imply to me that the temp files purr creates don't exist. Can you run purr with the following flag:

```
purr -D "/var/tmp/purr-test" 
```

That should create all of the files in that directory instead of the default tmp dir, and not delete them on program closure.

**Comment by ConorGarry** [comment]
Thanks for the response @alpiccioni .

Building the source and running gives the exact same results.

Running with the parameters `-D "/var/tmp/purr-test"` does give a slightly different result, but still ultimately doesn't work.

I now see this line when I run:
```
purr (main) $ ./out/purr -D "/var/tmp/purr-test"
mkfifo: /var/tmp/purr-test/thread_io_pipe: File exists
```

Again it just hangs, so I try `^C` to exit, but it then launches the full screen TUI, which still doesn't display any logs.

When I exit the TUI, with either `Esc` or `^C`, it returns to terminal, but with no prompt, and it doesn't react to any controls, though it will print their value to the screen (`^[` and `C`). At this point I have to close this window of iTerm and start a new one.

![CleanShot 2024-09-07 at 11 40 04@2x](https://github.com/user-attachments/assets/207dae03-02ea-4c6b-a331-5f31be5c1cef)

Sidenote: Another small bug I noticed (at least with my environment, the instructions in `^p` panel seem to loop over and over again. You can see in this screenshot where `Instructions` starts again right after the `Misc` section:

![CleanShot 2024-09-07 at 11 51 04@2x](https://github.com/user-attachments/assets/0a750d52-78d0-4ce2-a62e-2e50b37930c2)

**Comment by alpiccioni** [comment]
That's strange.

Can you grab the output directory and zip it up and send it over? What's happening in the files (which captures the state of the program) might give a hint.
